NstpSystem/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('nstpApp.urls')),
    path('admin/', admin.site.urls),
]

nstpApp/urls.py
from django.urls import path
from . import views
from django.conf.urls import static
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from django.urls import include, re_path

# password reset
from django.contrib.auth import views as auth_views



app_name = 'activities'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('adminlogin/', views.adminlogin, name='adminlogin'),
    path('orglogin/', views.orglogin, name='orglogin'),
    path('register/', views.register, name='register'),
    path('studentnav/', views.studentnav, name='studentnav'),
    # path('registration/', views.registration, name='registration'),
    path('registerprocess/', views.registerprocess, name='registerprocess'),
    path('userlogin/', views.userlogin, name='userlogin'),
    path('adregister/', views.adregister, name='adregister'),
    path('adminreg/', views.adminreg, name='adminreg'),
    # path('navbar/', views.navbar, name='navbar'),
    path('new_navbar/', views.new_navbar, name='new_navbar'),
    path('new_navbarstudent', views.new_navbarstudent, name='new_navbarstudent'),
    path('rotclist/', views.rotclist, name='rotclist'),
    path('cwtslist/', views.cwtslist, name='cwtslist'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('platoon/', views.platoon, name='platoon'),
    path('cwtss/', views.cwtss, name='cwtss'),
    path('userlogout/', views.userlogout, name='userlogout'),
    path('certification/', views.certification, name='certification'),
    path('cert/', views.cert, name='cert'),
    path('enrollupdate/', views.enrollupdate, name='enrollupdate'),
    path('certi/', views.certi, name='certi'),
    # path('requested/', views.requested, name='requested'),
    path('admincertificate/', views.admincertificate, name='admincertificate'),
    path('navadmin', views.navadmin, name='navadmin'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('delete/<str:id>', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('admindashboard/', views.admindashboard, name='admindashboard'),
    path('navlanding/', views.navlanding, name='navlanding'),
    path('updateform/', views.updateform, name='updateform'),
    path('indexcard1/', views.indexcard1, name='indexcard1'),
    path('indexcard2/', views.indexcard2, name='indexcard2'),
    path('indexcard3/', views.indexcard3, name='indexcard3'),
    path('indexcard4/', views.indexcard4, name='indexcard4'),
    
    path('admincwtslist/', views.admincwtslist, name='admincwtslist'),
    path('adminrotclist/', views.adminrotclist, name='adminrotclist'),
    path('enrolledrotc/', views.enrolledrotc, name='enrolledrotc'),
    path('enrolledcwts/', views.enrolledcwts, name='enrolledcwts'),
    path('platoonupdate/', views.platoonupdate, name='platoonupdate'),
    path('sectionupdate/', views.sectionupdate, name='sectionupdate'),
    path('rotc_delete/<str:id>', views.rotc_delete, name='rotc_delete'),
    # path('alphacount/', views.alphacount, name='alphacount'),
    # path('counts/', views.counts, name='counts'),

    # path('admincwts/', views.admincwts, name='admincwts'),
    # path('cwtslist1', views.cwtslist1, name='cwtslist1'),
    
    # path('cwts_delete/<str:id>', views.cwts_delete, name='cwts_delete'),
    path('dashboardupload/', views.dashboardupload, name='dashboardupload'),
    path('footer/', views.footer, name='footer'),
    path('deleteimage/<str:id>', views.deleteimage, name='deleteimage'),
 
    path('deleteform/', views.deleteform, name='deleteform'),
    path('pdf/<str:id>', views.pdf, name='pdf'),
    path('pdfb/<str:id>', views.pdfb, name='pdfb'),
    path('profile/', views.profile, name='profile'),
    #             ADMIN PLATOON UPLOAD
    path('alpha/', views.alpha, name='alpha'),
    path('bravo/', views.bravo, name='bravo'),
    path('charlie/', views.charlie, name='charlie'),
    path('delta/', views.delta, name='delta'),
    path('echo/', views.echo, name='echo'),
    path('foxtrot/', views.foxtrot, name='foxtrot'),
    path('golf/', views.golf, name='golf'),
    path('hotel/', views.hotel, name='hotel'),
    path('india/', views.india, name='india'),
    path('juliet/', views.juliet, name='juliet'),
    path('kilo/', views.kilo, name='kilo'),
    path('lima/', views.lima, name='lima'),

    
    #             END OF ADMIN PLATOON UPLOADS

#                    START OD ADMIN PLATOON DISPLAY
    path('adminplatoon/', views.adminplatoon, name='adminplatoon'),
    path('d_alpha/', views.d_alpha, name='d_alpha'),
    path('d_bravo/', views.d_bravo, name='d_bravo'),
    path('d_charlie/', views.d_charlie, name='d_charlie'),
    path('d_delta/', views.d_delta, name='d_delta'),
    path('d_echo/', views.d_echo, name='d_echo'),
    path('d_foxtrot/', views.d_foxtrot, name='d_foxtrot'),
    path('d_golf/', views.d_golf, name='d_golf'),
    path('d_hotel/', views.d_hotel, name='d_hotel'),
    path('d_india/', views.d_india, name='d_india'),
    path('d_juliet/', views.d_juliet, name='d_juliet'),
    path('d_kilo/', views.d_kilo, name='d_kilo'),
    path('d_lima/', views.d_lima, name='d_lima'),
    path('adcwts/', views.adcwts, name='adcwts'),
    path('cwtsupload/', views.cwtsupload, name='cwtsupload'),
    path('sectionbupload/', views.sectionbupload, name='sectionbupload'),
    path('sectioncupload/', views.sectioncupload, name='sectioncupload'),
    path('section_a/', views.section_a, name='section_a'),
    path('section_b/', views.section_b, name='section_b'),
    path('section_c/', views.section_c, name='section_c'),
    path('sectiona_delete/<str:id>', views.sectiona_delete, name='sectiona_delete'),
    path('sectionb_delete/<str:id>', views.sectionb_delete, name='sectionb_delete'),
    path('sectionc_delete/<str:id>', views.sectionc_delete, name='sectionc_delete'),
    
    
    

#                    END OF ADMIN PLATOON DISPLAY
    
    
                 # STUDENT PLATOON DISPLAY
    
    path('student_alpha/', views.student_alpha, name='student_alpha'),
    path('student_bravo/', views.student_bravo, name='student_bravo'),
    path('student_charlie/', views.student_charlie, name='student_charlie'),
    path('student_delta/', views.student_delta, name='student_delta'),
    path('student_echo/', views.student_echo, name='student_echo'),
    path('student_foxtrot/', views.student_foxtrot, name='student_foxtrot'),
    path('student_golf/', views.student_golf, name='student_golf'),
    path('student_hotel/', views.student_hotel, name='student_hotel'),
    path('student_india/', views.student_india, name='student_india'),
    path('student_juliet/', views.student_juliet, name='student_juliet'),
    path('student_kilo/', views.student_kilo, name='student_kilo'),
    path('student_lima/', views.student_lima, name='student_lima'),
    
#                       END OF STUDENT PLATOON DISPLAY
  
    
    
     
#                     START OF PLATOON DELETION
    
    path('alpha_delete/<str:id>', views.alpha_delete, name='alpha_delete'),
    path('bravo_delete/<str:id>', views.bravo_delete, name='bravo_delete'),
    path('charlie_delete/<str:id>', views.charlie_delete, name='charlie_delete'),
    path('delta_delete/<str:id>', views.delta_delete, name='delta_delete'),
    path('echo_delete/<str:id>', views.echo_delete, name='echo_delete'),
    path('foxtrot_delete/<str:id>', views.foxtrot_delete, name='foxtrot_delete'),
    path('golf_delete/<str:id>', views.golf_delete, name='golf_delete'),
    path('hotel_delete/<str:id>', views.hotel_delete, name='hotel_delete'),
    path('india_delete/<str:id>', views.india_delete, name='india_delete'),
    path('juliet_delete/<str:id>', views.juliet_delete, name='juliet_delete'),
    path('kilo_delete/<str:id>', views.kilo_delete, name='kilo_delete'),
    path('lima_delete/<str:id>', views.lima_delete, name='lima_delete'),
    
    path('section1/', views.section1, name='section1'),
    path('section2/', views.section2, name='section2'),
    path('section3/', views.section3, name='section3'),
    
#                     END OF PLATOON DELETION

    path('approval/', views.approval, name='approval'),
    path('email/', views.email, name='email'),
    path('sendmail_confirm/', views.sendmail_confirm, name='sendmail_confirm'),
    path('sendmail_manual/', views.sendmail_manual, name='sendmail_manual'),
    path('custom/', views.custom, name='custom'),
    path('custemail/<str:id>', views.custemail, name='custemail'),
    
    
    # passworrrdd reset path
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PaswwordResetCompleteView.as_view(), name='password_reset_complete'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nstpApp/models.py
import email
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# class MyAccountManager(BaseUserManager):
#     def create_user(self, email, username, password, **extra_fields):
#         if not email:
#             raise ValueError(_("Users must have an email address"))
#         if not username:
#             raise ValueError(_("Users must have an username address"))
        
#         user = self.model(
#             email=self.normalize_email(email), 
#             username=username,
#             )
#         user.set_password(password)
#         user.save(using=self._db)
#         return user
    
#     def create_superuser(self, email, username, password, **extra_fields):
#         user = self.create_user(
#             email=self.normalize_email(email),
#             password = password,
#             username=username,
#         )
#         user.is_admin = True
#         user.is_staff = True
#         user.is_superuser = True
#         user.save(using=self._db)
#         return user

        
        



class extenduser(models.Model):
    STATUS = (
    ("PENDING", "PENDING"),
    ("ENROLLED", "ENROLLED"),
    )
    
    GRADE = (
        ("PENDING", "PENDING"),
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),
        
    )

    field_rotc = 0
    field_cwts = 1
    field_choices = [(field_rotc, 'ROTC'), (field_cwts, 'CWTS')]
    platoon = models.CharField(max_length=10, blank=True, null=True)
    lname = models.CharField(max_length=20, default='')
    fname = models.CharField(max_length=30, default='')
    minitial = models.CharField(max_length=3, default='')
    address = models.CharField(max_length=100, default='')
    cpnumber = models.DecimalField(max_digits=11, decimal_places=0, default='')
    email = models.EmailField(max_length=254, null=True, unique=True)
    gender = models.CharField(max_length=6, default='')
    age = models.DecimalField(max_digits=3, decimal_places=0)
    bdate = models.CharField(max_length=15, default='')
    password = models.CharField(max_length=20)
    grades = models.CharField(max_length=20, choices=GRADE, default='PENDING')
    grades1 = models.CharField(max_length=20, choices=GRADE, default='PENDING')
    section = models.CharField(max_length=20, default='')
    field = models.CharField(max_length=20, default='')
    picture = models.ImageField(upload_to='images/', null=False)
    status = models.CharField(max_length=10, choices=STATUS, default='PENDING')
    cert_datereq = models.CharField(max_length=20, default='') 
    cert_document = models.CharField(max_length=20, default='') 
    cert_status = models.CharField(max_length=20, choices=STATUS, default='PENDING')
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # sendmail = models.CharField(max_length=20, default='PENDING')
    

    
    def __str__(self):
    
        return self.email
    

    

class certifications(models.Model):
    STATUS = (
        ("PENDING", "PENDING"),
        ("APPROVED", "APPROVED"),
        )
    cert_email = models.EmailField(max_length=254, null=True)
    cert_fullname = models.CharField(max_length=100)
    cert_course = models.CharField(max_length=20 )
    cert_datereq = models.CharField(max_length=20 )
    cert_document = models.CharField(max_length=20 )
    cert_status = models.CharField(max_length=20, choices=STATUS, default='PENDING')
  
    
    def __str__(self):
        return self.cert_email
    
    
    
# platons

class alphamodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    # alphaImage = models.ImageField(upload_to='images/', null=False)
    def __str__(self):
        return self.name
    
class bravomodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
class charliemodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
    
class deltamodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

class echomodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
class foxtrotmodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
    
class golfmodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
    
class hotelmodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
    
class indiamodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
class julietmodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
    
class kilomodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
class limamodel(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    

    
    
class carousel(models.Model):
    imagefile= models.ImageField(upload_to='images/', null=True)
    
    def __str__(self):
        return self.imagefile
    
    
    
class sectiona(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
class sectionb(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
class sectionc(models.Model):
    name = models.CharField(max_length=20)
    pdf= models.FileField(upload_to='pdf/')
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    

nstpApp/forms.py
from django.forms import ModelForm

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

nstpApp/templates/activities/admindelta.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>delta</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <link rel="stylesheet" href="{% static 'css_admin/alpha.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>

<body>
    {% include 'activities/NavAdmin.html' %}


    <div class="card text-center">
        <div class="card-header">
            DELTA COMPANY
        </div>


    </div>

    <!-- uploads -->
    <div class="fortit">
        <form action="{% url 'activities:delta' %}" method="POST" enctype="multipart/form-data" name="files">
            {% csrf_token %}

            <div class="uploads">

                <div class="left col-6">
                    <h1 id="uploadx">Upload File Here</h1>
                    <div class="container1">
                        <div class="row it">
                            <div class="col-sm-offset-1 col-sm-10" id="one">
                                <p>
                                    Please upload documents only in 'pdf', 'docx', 'rtf', 'jpg', 'jpeg', 'png' & 'text' format.
                                </p><br>
                                <div class="row">
                                    <div class="col-sm-offset-4 col-sm-4 form-group">
                                        <h3 class="text-center">My Documents</h3>
                                    </div>
                                    <!--form-group-->
                                </div>
                                <!--row-->


                                <div id="uploader">
                                    <div class="row uploadDoc">
                                        <div class="col-sm-3">
                                            <div class="docErr">Please upload valid file</div>
                                            <!--error-->
                                            <div class="fileUpload btn btn-orange">
                                                <img src="{% static 'image/upload.png' %}" class="icon">
                                                <span class="upl" id="upload">Upload document</span>
                                                <input type="file" name="document" class="upload up" id="up" onchange="readURL(this);" />
                                            </div>
                                            <!-- btn-orange -->
                                        </div>
                                        <!-- col-3 -->
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="notes" placeholder="Filename">
                                        </div>
                                        <!--col-8-->
                                        <div class="col-sm-1"><a class="btn-check"><i class="fa fa-times"></i></a></div>
                                        <!-- col-1 -->
                                    </div>
                                    <!--row-->
                                </div>
                                <!--uploader-->
                                <div class="text-center">
                                    <button class="btn btn-next" type="submit" onclick="submitForm()"><i class="fa fa-paper-plane" ></i> Submit</button>
                                </div>

                            </div>
                            <!--one-->
                        </div>
                        <!-- row -->
                    </div>

                </div>

                <div class="right col-6">
                    <h1 id="uploadx">View File Here</h1>
                    <table class="table table-hover">
                        <thead class="thead-dark">
                            <tr>

                                <th scope="col" class="center">Filename</th>
                                <th scope="col" class="center" style="text-align: center;">DOWNLOAD FILE</th>
                                <th scope="col" class="center" style="text-align: center;">DELETE FILE</th>

                            </tr>
                        </thead>

                        <tbody>
                            {% for file in delta_display %}

                            <tr>

                                <td>{{file.name}}</td>

                                <td>{% if file.pdf %}
                                    <button class="pdf" disabled><a style="text-decoration:none" href="{{file.pdf.url}}" target="__blank"><i class="fa fa-download" aria-hidden="true"> Download</i></a></button> {% endif %}

                                </td>
                                <td><button class="delete" disabled><a style="text-decoration:none" href="{% url 'activities:delta_delete' file.id %}" ><i class="fa fa-trash" aria-hidden="true"> Delete</i></a></button></td>

                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                </div>

                <!-- container -->

            </div>
        </form>

    </div>
    <br> <br> <br>
    <div>
        <h1 style="text-align: center; margin:auto;">Students Grade</h1>
        <div class="hehe">
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">FULL NAME</th>
                        <th scope="col">Email</th>
                        <th scope="col">Course and Section</th>
                        <th scope="col">Grade</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for v in delta_grade %}
                    <tr>
                        <th scope="row">{{v.fname}} {{v.lname}}</th>
                        <td>{{v.email}}</td>
                        <td>{{v.section}}</td>
                        <form action="{% url 'activities:d_delta' %}" method="POST">
                            {% csrf_token %}

                            <td><input type="text" name="d_grades" value="{{v.grades}}" style="color: rgb(0, 0, 0); width:100px;">
                                <input type="text" name="d_grades1" value="{{v.grades1}}" style="color: rgb(0, 0, 0); width:100px;">
                            </td>
                            <td><input type="hidden" name="delta_id" value="{{v.id}}"><button class="update" id="submit" onclick="status()" type="submit"><i class="fa fa-check-circle" aria-hidden="true" style="color: rgb(8, 162, 0);">SAVE</i></button></td>

                        </form>
                    </tr>

                    {% endfor %}

                </tbody>
            </table>

        </div>
    </div>




    <!-- modal -->

    <!-- <iframe width="420" height="345" src="https://www.youtube.com/embed/tgbNymZ7vqY?autoplay=1&mute=1">
    </iframe> -->


    <script>
        function myFunction() {
            document.getElementById("files").reset();
        }
    </script>




    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <script src="{% static 'js_admin/alpha.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>


</body>

</html>

nstpApp/templates/activities/alphadel.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'css/delete.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>

<body>
    <div class="del">
        <form action="#" method="post">
            {% csrf_token %}
            <h1>Are you sure you want to delete?</h1><br>
            <div class="buttons">
                <input class="btn btn-danger" type="submit" value="Yes"><br>&nbsp;
                <a href="/d_alpha" style="text-decoration: none;">
                    <div class="btn btn-primary">Cancel</div>
                </a>

            </div>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
</body>

</html>

nstpApp/templates/activities/foxtrotdel.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'css/delete.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>

<body>
    <div class="del">
        <form action="#" method="post">
            {% csrf_token %}
            <h1>Are you sure you want to delete?</h1><br>
            <div class="buttons">
                <input class="btn btn-danger" type="submit" value="Yes"><br>&nbsp;
                <a href="/d_foxtrot" style="text-decoration: none;">
                    <div class="btn btn-primary">Cancel</div>
                </a>

            </div>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
</body>

</html>